import { GoogleGenAI } from '@google/genai';
import { logger } from '../../utils/logger';
import { config, DEFAULT_GEMINI_MODEL } from '../../config';
import {
  SummaryContent,
  FlashcardsContent,
  CourseContent,
  QuizContent
} from '../../database/models/AiOutput.model';
import mongoose from 'mongoose';

const MAX_CONTENT_LENGTH = 10000;

class AiService {
  private ai: GoogleGenAI | null = null;
  private model: string;

  constructor() {
    this.model = config.gemini.model || DEFAULT_GEMINI_MODEL;
    if (config.gemini.apiKey) {
      this.ai = new GoogleGenAI({ apiKey: config.gemini.apiKey });
    } else {
      logger.warn('Gemini API key not configured. AI features will use mock data.');
    }
  }

  /**
   * Strip markdown code fences that Gemini sometimes wraps around JSON
   */
  private parseJson<T>(raw: string): T {
    const cleaned = raw.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/i, '').trim();
    return JSON.parse(cleaned) as T;
  }

  /**
   * Generate summary from content
   */
  async generateSummary(content: string): Promise<SummaryContent> {
    try {
      if (!this.ai) {
        return this.mockSummary(content);
      }

      const prompt = `You are an expert educational content analyst. Your task is to produce a concise, structured summary of the provided article or webpage content.

Return ONLY valid JSON — no markdown, no explanation, no code fences.

Required JSON schema:
{
  "keyPoints": string[],     // 3-5 distinct, specific main points from the content
  "mainArgument": string,    // The central thesis or purpose in 1-2 clear sentences
  "takeaways": string[]      // 3-5 actionable or memorable insights a reader should retain
}

Rules:
- keyPoints and takeaways must be concrete and specific to the content, not generic
- mainArgument must accurately capture the core message
- Do not include any text outside the JSON object

Content to summarize (up to ${MAX_CONTENT_LENGTH} characters):
---
${content.substring(0, MAX_CONTENT_LENGTH)}
---`;

      const response = await this.ai.models.generateContent({
        model: this.model,
        contents: prompt
      });

      const responseText = response.text ?? '';
      if (!responseText) {
        throw new Error('Empty response from Gemini');
      }

      const parsed = this.parseJson<SummaryContent>(responseText);

      if (!parsed.keyPoints || !parsed.mainArgument || !parsed.takeaways) {
        throw new Error('Invalid summary structure returned by Gemini');
      }

      return parsed;
    } catch (error: any) {
      logger.error('Error generating summary:', error);
      throw error;
    }
  }

  /**
   * Generate flashcards from content
   */
  async generateFlashcards(content: string): Promise<FlashcardsContent> {
    try {
      if (!this.ai) {
        return this.mockFlashcards(content);
      }

      const prompt = `You are an expert educational flashcard creator. Generate study flashcards from the provided content that test genuine understanding, not trivia.

Return ONLY valid JSON — no markdown, no explanation, no code fences.

Required JSON schema:
{
  "flashcards": [
    {
      "question": string,                          // A clear, specific question targeting a key concept
      "answer": string,                            // A concise, accurate answer (1-3 sentences)
      "difficulty": "easy" | "medium" | "hard"    // Calibrated to how core/complex the concept is
    }
  ]
}

Rules:
- Generate between 5 and 10 flashcards
- Progressively cover easy conceptual questions through harder application/analysis questions
- Questions must be directly answerable from the provided content
- Do not include any text outside the JSON object

Content (up to ${MAX_CONTENT_LENGTH} characters):
---
${content.substring(0, MAX_CONTENT_LENGTH)}
---`;

      const response = await this.ai.models.generateContent({
        model: this.model,
        contents: prompt
      });

      const responseText = response.text ?? '';
      if (!responseText) {
        throw new Error('Empty response from Gemini');
      }

      const parsed = this.parseJson<FlashcardsContent>(responseText);

      if (!parsed.flashcards || parsed.flashcards.length < 3) {
        throw new Error('Not enough flashcards generated by Gemini');
      }

      return parsed;
    } catch (error: any) {
      logger.error('Error generating flashcards:', error);
      throw error;
    }
  }

  /**
   * Generate course from multiple summaries
   */
  async generateCourse(summaries: SummaryContent[]): Promise<CourseContent> {
    try {
      if (!this.ai) {
        return this.mockCourse(summaries);
      }

      const summariesText = summaries
        .map((s, i) =>
          `[Source ${i + 1}]\nMain argument: ${s.mainArgument}\nKey points:\n${s.keyPoints.map(p => `  - ${p}`).join('\n')}\nTakeaways:\n${s.takeaways.map(t => `  - ${t}`).join('\n')}`
        )
        .join('\n\n');

      const prompt = `You are a senior curriculum designer. Synthesize the following learning resource summaries into a single cohesive course with clearly structured lessons.

Return ONLY valid JSON — no markdown, no explanation, no code fences.

Required JSON schema:
{
  "title": string,           // A compelling, specific course title reflecting the combined content
  "description": string,     // 2-3 sentence overview of what students will learn and why it matters
  "lessons": [
    {
      "title": string,       // lesson title, keep it concise and catchy
      "content": string,     // Rich lesson body (at least 3-5 sentences) synthesising relevant source material
      "order": number        // 1-indexed lesson order
    }
  ]
}

Rules:
- Produce at least 3 lessons, one per major theme that emerges from the sources
- Lessons must flow logically from foundational concepts to advanced application
- Each lesson content must be educational prose, not just bullet points
- Do not include any text outside the JSON object

Source summaries:
---
${summariesText}
---`;

      const response = await this.ai.models.generateContent({
        model: this.model,
        contents: prompt
      });

      const responseText = response.text ?? '';
      if (!responseText) {
        throw new Error('Empty response from Gemini');
      }

      const parsed = this.parseJson<CourseContent>(responseText);

      if (!parsed.title || !parsed.lessons || parsed.lessons.length < 2) {
        throw new Error('Invalid course structure returned by Gemini');
      }

      return parsed;
    } catch (error: any) {
      logger.error('Error generating course:', error);
      throw error;
    }
  }

  /**
   * Generate quiz from course content
   */
  async generateQuiz(courseContent: CourseContent, courseId?: mongoose.Types.ObjectId): Promise<QuizContent> {
    try {
      if (!this.ai) {
        return this.mockQuiz(courseContent, courseId);
      }

      const lessonsText = courseContent.lessons
        .map(l => `Lesson ${l.order} — ${l.title}:\n${l.content.substring(0, 400)}`)
        .join('\n\n');

      const prompt = `You are an expert educational assessment designer. Create a multiple-choice quiz that rigorously tests understanding of the course material below.

Return ONLY valid JSON — no markdown, no explanation, no code fences.

Required JSON schema:
{
  "questions": [
    {
      "question": string,      // A clear, unambiguous question about the lesson content
      "options": string[],     // Exactly 4 options — one correct, three plausible distractors
      "correct": number,       // 0-based index of the correct option in the options array
      "explanation": string    // 1-2 sentence explanation of why the correct answer is right
    }
  ]
}

Rules:
- Generate between 5 and 15 questions, proportional to the number of lessons
- Each lesson must be covered by at least one question
- Distractors must be plausible (not obviously wrong)
- Questions must test comprehension and application, not just recall
- Do not include any text outside the JSON object

Course: ${courseContent.title}

Lessons:
---
${lessonsText.substring(0, 4000)}
---`;

      const response = await this.ai.models.generateContent({
        model: this.model,
        contents: prompt
      });

      const responseText = response.text ?? '';
      if (!responseText) {
        throw new Error('Empty response from Gemini');
      }

      const parsed = this.parseJson<QuizContent>(responseText);

      if (!parsed.questions || parsed.questions.length < 3) {
        throw new Error('Not enough quiz questions generated by Gemini');
      }

      if (courseId) {
        parsed.courseId = courseId;
      }

      return parsed;
    } catch (error: any) {
      logger.error('Error generating quiz:', error);
      throw error;
    }
  }

  // Mock implementations for when Gemini is not configured
  private mockSummary(content: string): SummaryContent {
    const words = content.split(' ').slice(0, 100);
    return {
      keyPoints: [
        words.slice(0, 20).join(' ') + '...',
        words.slice(20, 40).join(' ') + '...',
        words.slice(40, 60).join(' ') + '...'
      ],
      mainArgument: 'This content provides educational information on the topic.',
      takeaways: [
        'Key takeaway from the content',
        'Important concept to remember',
        'Practical application of the knowledge'
      ]
    };
  }

  private mockFlashcards(content: string): FlashcardsContent {
    return {
      flashcards: Array.from({ length: 5 }).map((_, i) => ({
        question: `Question ${i + 1} about the content?`,
        answer: `Answer ${i + 1} explaining the concept from the content.`,
        difficulty: i < 2 ? 'easy' : i < 4 ? 'medium' : 'hard' as const
      }))
    };
  }

  private mockCourse(summaries: SummaryContent[]): CourseContent {
    return {
      title: 'Course Generated from Your Links',
      description: 'A comprehensive course synthesized from your saved resources.',
      lessons: summaries.map((summary, index) => ({
        title: `Lesson ${index + 1}: ${summary.mainArgument.substring(0, 50)}...`,
        content: `${summary.mainArgument}\n\n${summary.keyPoints.join('\n')}`,
        order: index + 1
      }))
    };
  }

  private mockQuiz(courseContent: CourseContent, courseId?: mongoose.Types.ObjectId): QuizContent {
    return {
      courseId,
      questions: Array.from({ length: 5 }).map((_, i) => ({
        question: `Question ${i + 1} about the course content?`,
        options: [
          'Correct answer with explanation',
          'Plausible but incorrect option',
          'Another incorrect option',
          'Final incorrect option'
        ],
        correct: 0,
        explanation: `Explanation for why option 0 is correct.`
      }))
    };
  }
}

const aiService = new AiService();
export default aiService;
export { aiService };
